# Generated by Django 5.2.7 on 2025-11-08 01:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0003_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rows', models.IntegerField(default=10)),
                ('seats_per_row', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('price_standard', models.DecimalField(decimal_places=2, default=Decimal('150'), max_digits=6)),
                ('price_premium', models.DecimalField(decimal_places=2, default=Decimal('250'), max_digits=6)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_schedule.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_sessions', to='movies.movie')),
            ],
            options={
                'unique_together': {('hall', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('seat', models.IntegerField()),
                ('is_booked', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movie_schedule.session')),
            ],
            options={
                'unique_together': {('session', 'row', 'seat')},
            },
        ),
    ]
