# Generated by Django 5.2.7 on 2025-10-17 09:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=40, null=True, unique=True)),
                ('fname', models.CharField(max_length=50, verbose_name='first name')),
                ('lname', models.CharField(max_length=50, verbose_name='last name')),
                ('sex', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='o', max_length=30)),
                ('birthday', models.DateField()),
                ('client_type', models.CharField(choices=[('cli', 'Client'), ('emp', 'Employee'), ('pen', 'Pensioner'), ('nd', 'Not Defined'), ('sk', 'Schoolkid'), ('st', 'Student')], default='nd', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
