# Generated by Django 5.2.7 on 2025-10-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client_type',
            field=models.CharField(choices=[('cli', 'Client'), ('emp', 'Employee'), ('pen', 'Pensioner'), ('nd', 'Not Defined'), ('sk', 'Schoolkid'), ('st', 'Student')], default='nd', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='o', max_length=30),
        ),
    ]
