# Generated by Django 5.2.7 on 2025-10-17 11:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=4),
        ),
    ]
