# Generated by Django 5.2.7 on 2025-10-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_total_order_total_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_text',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
