# Generated by Django 5.2.7 on 2025-11-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderitem_price_orderitem_price_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
