# Generated by Django 5.2.7 on 2025-11-08 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_order_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
